baseURL = "https://whentheycamedown.com"
languageCode = "en"
title = "whentheycamedown"
theme = "hugo-nederburg-theme"

[taxonomies]
   tag = "tags"
   category = "categories"
   subject = "subjects"

[languages]
  [languages.en]
    contentDir = "content/english"
    languageName = "English"
    weight = 10
  [languages.es]
    contentDir = "content/espanol"
    languageName = "Español"
    weight = 20

[[languages.en.menu.main]]
url = "https://github.com/Gorcenski/whentheycamedown/blob/trunk/README.md"
name = "Contribute"
weight = 1
[[languages.en.menu.main]]
url = "/about/"
name = "About"
weight = 2
# [[languages.en.menu.main]]
# url = "/es/"
# name = "Español"
# weight = 2
[[languages.es.menu.main]]
url = "https://github.com/Gorcenski/whentheycamedown/blob/trunk/README.md"
name = "Contribuir"
weight = 1
[[languages.es.menu.main]]
url = "/about/"
name = "Acerca"
weight = 2
[[languages.es.menu.main]]
url = "/"
name = "English"
weight = 3
# [[menu.main]]
# url = "/tags"
# name = "Tags"
# weight = 4
# [[menu.main]]
# url = "/posts"
# name = "Archive"
# weight = 1
# # [[menu.main]]
# # url = "/episodes"
# # name = "Episodes"
# # weight = 2
# [[menu.main]]
# url = "/index.xml"
# name = "RSS Feed"
# weight = 5
